package com.tt.handsomeman.util

object MessageConstant {
    val JOB_NOT_FOUND = "Job not found"
    val EMAIL_IS_USED = "Email is used"
    val NOT_FOUND_CUSTOMER_REVIEW = "Not found customer review"
    val NO_JOBS_IN_THIS_CATEGORY = "No job in this category"
    val FACEBOOK_TOKEN_IS_EXPIRED = "Facebook token is expired"
    val FB_NOT_LOGIN = "Can not login Facebook"
    val EMAIL_PASSWORD_WRONG = "Email or password wrong"
    val EMAIL_NOT_RIGHT = "Email not right"
    val CUSTOMER_NOT_FOUND_BY_ACCOUNT = "Customer not found by account"
    val ACCOUNT_NOT_FOUND_BY_MAIL = "Account not found by mail"
    val HANDY_MAN_NOT_FOUND_BY_ACCOUNT = "Handyman not found by account"
    val JOB_IS_BIDDEN_SUCCESSFULLY = "Job is bidden successfully"
    val JOB_DELETED_SUCCESSFULLY = "Job deleted successfully"
    val JOB_UPDATED_SUCCESSFULLY = "Job updated successfully"
    val JOB_ADDED_SUCCESSFULLY = "Job added successfully"
    val USER_CREATED = "New user have just been created successfully"
    val BID_MAX_SMALLER_THAN_BID_MIN = "Bid max is small than bid min"
    val UNAUTHORIZED = "Unauthorized"
    val ACCESS_DENIED = "Access denied"
    val USER_NOT_FOUND = "Cannot found user with username and password"

    val EMAIL_NOT_VALID = "Email is not valid"
    val USER_CVR = "CVR"
    val USER_CPR = "CPR"
    val SERVER_ERROR = "Server error"
    val CODE_NOT_RIGHT = "Code not right"
    val PASSWORD_CHANGED = "Password have just been changed"
    val CODE_SEND_EMAIL = "Code just send to your email"
    val CODE_RESET_PASS = "Code to reset your password"
    val ROLE_USER = "ROLE_CUSTOMER"
    val ROLE_HANDYMAN = "ROLE_HANDYMAN"
    val CODE_IS_EMPTY = "Code is empty"
    val PASS_IS_EMPTY = "Password is empty"
    val PASS_NOT_MATCH = "Password and RePassword not matches"
    val NAME_IS_EMPTY = "Name is empty"
    val FIRST_NAME_IS_EMPTY = "First name is empty"
    val LAST_NAME_IS_EMPTY = "Last name not empty"
    val TYPE_IS_EMPTY = "Type is empty"
    val ADDRESS_IS_EMPTY = "Address is empty"
    val PORTAL_CODE_IS_EMPTY = "Portal code is empty"
    val USER_INFO_ADDED = "User information have just been added"
    val ACCOUNT_IS_EMPTY = "Account is empty"
    val ROUTING_IS_EMPTY = "Routing is empty"
    val COUNTRY_IS_EMPTY = "Country is empty"
    val USER_UPGRADE_CVR = "User have just been updated to CVR"
    val NUMBER_IS_EMPTY = "Number is empty"
    val GENERIC_ERROR = "Generic error"
    val DUMMY_REQUEST = "Dummy request"
    val WITHDRAW_SUCCESSFUL = "Withdraw successful"
    val WITHDRAW_FAIL = "Withdraw fail, the money in wallet not enough"
    val WITHDRAW_FAIL_HANDYMAN_CREDIT_CARD = "Withdraw fail, can't find handyman or credit card"
}
